# Generated by Django 4.0.3 on 2022-03-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='matches',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='theme',
            name='missing_word',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='theme',
            name='right_answer',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='theme',
            name='right_order',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theory',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='theme',
            name='video',
            field=models.CharField(max_length=1000),
        ),
    ]
