# Generated by Django 4.0.3 on 2022-04-24 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_alter_theme_matches_alter_theme_missing_word_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
    ]
